[package]
name = "stafi-crypto"
version = "0.1.0"
authors = ["Howie <howie@bitstarlight.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsodium-sys = "0.2.4"
bitcoin = "0.20.0"
tiny-bip39 = "0.6.2"

[dev-dependencies]
hex-literal = "0.2"